# Generated by Django 4.0.4 on 2022-04-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_rackets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='amount_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racket',
            name='overall_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
