# Generated by Django 4.0.4 on 2022-04-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_rackets_app', '0002_racket_amount_of_votes_racket_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rackets/'),
        ),
    ]
