# Generated by Django 4.0.4 on 2022-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_rackets_app', '0003_alter_racket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='rackets_secondary/'),
        ),
    ]
