# Generated by Django 4.0.4 on 2022-04-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_rackets_app', '0005_racket_points_ratingcomment_overallracketrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racket',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
