# Generated by Django 4.0.4 on 2022-04-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_rackets_app', '0008_alter_overallracketrating_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcomment',
            name='amounts_of_down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratingcomment',
            name='amounts_of_up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
