# Generated by Django 4.0.4 on 2022-04-21 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_remove_userprofile_id_alter_userprofile_user'),
        ('comments_rackets_app', '0009_ratingcomment_amounts_of_down_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(default='NO VOTE', max_length=50)),
                ('rating_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments_rackets_app.ratingcomment')),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.userprofile')),
            ],
        ),
    ]
