# Generated by Django 4.0.4 on 2022-04-17 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('profile_icon', models.CharField(default='Racket', max_length=50)),
                ('profile_icon_color', models.CharField(default='#38b6ff', max_length=10)),
                ('profile_icon_color_mode', models.BooleanField(default=True)),
                ('amounts_of_comments', models.IntegerField(default=0)),
                ('amounts_of_up_votes', models.IntegerField(default=0)),
                ('amounts_of_down_votes', models.IntegerField(default=0)),
                ('amounts_of_received_up_votes', models.IntegerField(default=0)),
                ('amounts_of_received_down_votes', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
